spring.application.name=smart_civic
server.port=8081
spring.datasource.url=jdbc:h2:file:C:/Users/thanu/.gemini/antigravity/scratch/smart-civic/smart_civic/smart-civic-db/smartcivicdb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
# JWT Secret (should be more secure in production)
jwt.secret=9a674713da6f437090870932822a9459223871404a11277a8342462e08048293
jwt.expiration=86400000
spring.jpa.open-in-view=false
